/*
Navicat SQL Server Data Transfer

Source Server         : GAMS
Source Server Version : 140000
Source Host           : DESKTOP-36C9L6T:1433
Source Database       : lushushu
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 140000
File Encoding         : 65001

Date: 2019-06-24 14:15:54
*/


-- ----------------------------
-- Table structure for [dbo].[GAMSresult]
-- ----------------------------
DROP TABLE [dbo].[GAMSresult]
GO
CREATE TABLE [dbo].[GAMSresult] (
[Pid] varchar(32) NULL ,
[Tid1] varchar(32) NULL ,
[Tid2] varchar(32) NULL ,
[id] varchar(10) NULL ,
[number] bigint NULL ,
[nowdaystime] datetime NULL 
)


GO

-- ----------------------------
-- Records of GAMSresult
-- ----------------------------

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_PERSON_ON_DUTY]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_PERSON_ON_DUTY]
GO
CREATE TABLE [dbo].[IMS_PATROL_PERSON_ON_DUTY] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NULL ,
[SKILL_LEVEL] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_PERSON_ON_DUTY
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0001', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0002', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0003', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0004', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0005', N'3');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_PERSON_TASK_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_PERSON_TASK_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_PERSON_TASK_TIME] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NULL ,
[TASK_ID] varchar(32) NULL ,
[SPEND_TIME] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_PERSON_TASK_TIME
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0001', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0002', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0002', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0004', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0006', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0006', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0008', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0008', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0009', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0010', N'35');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS00', N'120');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_ROUTE_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_ROUTE_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_ROUTE_TIME] (
[ID] bigint NOT NULL ,
[PERSON_ID] varchar(32) NOT NULL ,
[FROM_TASK_ID] varchar(32) NOT NULL ,
[TO_TASK_ID] varchar(32) NOT NULL ,
[ORDER_NO] int NOT NULL ,
[SPEND_TIME] int NOT NULL ,
[START_TIME] datetime NOT NULL ,
[END_TIME] datetime NOT NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_ROUTE_TIME
-- ----------------------------

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_SKILL]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_SKILL]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_SKILL] (
[ID] bigint NULL ,
[TASK_ID] varchar(32) NULL ,
[SKILL_LEVEL] int NULL ,
[TASK_PRIORITY] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_SKILL
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0000', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0001', N'1', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0002', N'2', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0003', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0004', N'1', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0005', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0006', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0007', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0008', N'2', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0009', N'1', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0010', N'1', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS00', N'3', N'2');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_SPEND_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_SPEND_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_SPEND_TIME] (
[ID] bigint NULL ,
[FROM_TASK_ID] varchar(32) NULL ,
[TO_TASK_ID] varchar(32) NULL ,
[SPEND_TIME] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_SPEND_TIME
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0000', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0000', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0000', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0000', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0000', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0000', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0000', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0000', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0000', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0000', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0000', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0001', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0001', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0001', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0001', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0001', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0001', N'54');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0001', N'76');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0001', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0001', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0001', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0001', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0002', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0002', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0002', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0002', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0002', N'19');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0002', N'57');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0002', N'16');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0002', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0002', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0002', N'72');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0002', N'28');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0003', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0003', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0003', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0003', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0003', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0003', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0003', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0003', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0003', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0003', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0004', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0004', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0004', N'19');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0004', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0004', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0004', N'73');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0004', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0004', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0004', N'67');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0004', N'56');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0004', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0005', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0005', N'54');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0005', N'57');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0005', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0005', N'73');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0005', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0005', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0005', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0005', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0005', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0005', N'64');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0006', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0006', N'76');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0006', N'16');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0006', N'8');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0006', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0006', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0006', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0006', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0006', N'77');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0007', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0007', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0007', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0007', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0007', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0007', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0007', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0007', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0007', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0007', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0007', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0008', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0008', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0008', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0008', N'67');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0008', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0008', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0008', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0008', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0008', N'29');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0009', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0009', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0009', N'72');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0009', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0009', N'56');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0009', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0009', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0009', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0009', N'29');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0009', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0009', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0010', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0010', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0010', N'28');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0010', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0010', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0010', N'64');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0010', N'77');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0010', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0010', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0010', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0010', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS00', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0001', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0002', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0003', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0004', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0005', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0006', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0007', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0010', N'30');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_TIME] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NOT NULL ,
[TASK_ID] varchar(32) NOT NULL ,
[ORDER_NO] int NOT NULL ,
[SPEND_TIME] int NOT NULL ,
[START_TIME] datetime NOT NULL ,
[END_TIME] datetime NOT NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_TIME
-- ----------------------------
