/*
Navicat SQL Server Data Transfer

Source Server         : GAMS
Source Server Version : 140000
Source Host           : DESKTOP-36C9L6T:1433
Source Database       : lushushu
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 140000
File Encoding         : 65001

Date: 2019-06-26 16:26:15
*/


-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_PERSON_ON_DUTY]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_PERSON_ON_DUTY]
GO
CREATE TABLE [dbo].[IMS_PATROL_PERSON_ON_DUTY] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NULL ,
[SKILL_LEVEL] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_PERSON_ON_DUTY
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0001', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0002', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0003', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0004', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_ON_DUTY] ([ID], [PERSON_ID], [SKILL_LEVEL]) VALUES (null, N'XJ0005', N'3');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_PERSON_TASK_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_PERSON_TASK_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_PERSON_TASK_TIME] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NULL ,
[TASK_ID] varchar(32) NULL ,
[SPEND_TIME] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_PERSON_TASK_TIME
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0001', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0001', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0002', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0002', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0002', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0004', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0004', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0005', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0006', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0006', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0007', N'25');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0008', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0008', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0008', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0009', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0009', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS0010', N'35');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS0010', N'999999');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0001', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0003', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0002', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0004', N'TS00', N'120');
GO
INSERT INTO [dbo].[IMS_PATROL_PERSON_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [SPEND_TIME]) VALUES (null, N'XJ0005', N'TS00', N'120');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_ROUTE_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_ROUTE_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_ROUTE_TIME] (
[ID] bigint NOT NULL ,
[PERSON_ID] varchar(32) NOT NULL ,
[FROM_TASK_ID] varchar(32) NOT NULL ,
[TO_TASK_ID] varchar(32) NOT NULL ,
[ORDER_NO] int NOT NULL ,
[SPEND_TIME] int NOT NULL ,
[START_TIME] datetime NOT NULL ,
[END_TIME] datetime NOT NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_ROUTE_TIME
-- ----------------------------

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_SKILL]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_SKILL]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_SKILL] (
[ID] bigint NULL ,
[TASK_ID] varchar(32) NULL ,
[SKILL_LEVEL] int NULL ,
[TASK_PRIORITY] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_SKILL
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0000', N'3', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0001', N'1', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0002', N'2', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0003', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0004', N'1', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0005', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0006', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0007', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0008', N'2', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0009', N'1', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0010', N'1', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS00', N'3', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0011', N'2', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0012', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0013', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0014', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0015', N'2', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0016', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0017', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0018', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0019', N'2', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0020', N'2', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0021', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0022', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0023', N'1', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0024', N'3', N'2');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0025', N'2', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0026', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0027', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0028', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0029', N'3', N'3');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SKILL] ([ID], [TASK_ID], [SKILL_LEVEL], [TASK_PRIORITY]) VALUES (null, N'TS0030', N'2', N'3');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_SPEND_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_SPEND_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_SPEND_TIME] (
[ID] bigint NULL ,
[FROM_TASK_ID] varchar(32) NULL ,
[TO_TASK_ID] varchar(32) NULL ,
[SPEND_TIME] int NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_SPEND_TIME
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0000', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0000', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0000', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0000', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0000', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0000', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0000', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0000', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0000', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0000', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0000', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0001', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0001', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0001', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0001', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0001', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0001', N'54');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0001', N'76');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0001', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0001', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0001', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0001', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0002', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0002', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0002', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0002', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0002', N'19');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0002', N'57');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0002', N'16');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0002', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0002', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0002', N'72');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0002', N'28');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0003', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0003', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0003', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0003', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0003', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0003', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0003', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0003', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0003', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0003', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0003', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0004', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0004', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0004', N'19');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0004', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0004', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0004', N'73');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0004', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0004', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0004', N'67');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0004', N'56');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0004', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0005', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0005', N'54');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0005', N'57');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0005', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0005', N'73');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0005', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0005', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0005', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0005', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0005', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0005', N'64');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0006', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0006', N'76');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0006', N'16');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0006', N'8');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0006', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0006', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0006', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0006', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0006', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0006', N'77');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0007', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0007', N'44');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0007', N'7');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0007', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0007', N'82');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0007', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0007', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0007', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0007', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0007', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0007', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0008', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0008', N'61');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0008', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0008', N'67');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0008', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0008', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0008', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0008', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0008', N'29');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0009', N'20');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0009', N'31');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0009', N'72');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0009', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0009', N'56');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0009', N'78');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0009', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0009', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0009', N'29');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0009', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0009', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0000', N'TS0010', N'30');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0001', N'TS0010', N'63');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0002', N'TS0010', N'28');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0003', N'TS0010', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0004', N'TS0010', N'89');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0005', N'TS0010', N'64');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0006', N'TS0010', N'77');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0007', N'TS0010', N'40');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0008', N'TS0010', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0009', N'TS0010', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS0010', N'TS0010', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS00', N'0');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0000', N'1');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0001', N'10');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0002', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0003', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0004', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0005', N'50');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0006', N'60');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0007', N'70');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0008', N'90');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_SPEND_TIME] ([ID], [FROM_TASK_ID], [TO_TASK_ID], [SPEND_TIME]) VALUES (null, N'TS00', N'TS0010', N'30');
GO

-- ----------------------------
-- Table structure for [dbo].[IMS_PATROL_TASK_TIME]
-- ----------------------------
DROP TABLE [dbo].[IMS_PATROL_TASK_TIME]
GO
CREATE TABLE [dbo].[IMS_PATROL_TASK_TIME] (
[ID] bigint NULL ,
[PERSON_ID] varchar(32) NOT NULL ,
[TASK_ID] varchar(32) NOT NULL ,
[ORDER_NO] int NOT NULL ,
[SPEND_TIME] int NOT NULL ,
[START_TIME] datetime NOT NULL ,
[END_TIME] datetime NOT NULL 
)


GO

-- ----------------------------
-- Records of IMS_PATROL_TASK_TIME
-- ----------------------------
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0000', N'16', N'71', N'2019-06-25 17:18:00.000', N'2019-06-25 18:29:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS00', N'6', N'170', N'2019-06-25 11:09:00.000', N'2019-06-25 13:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0010', N'2', N'65', N'2019-06-25 08:30:00.000', N'2019-06-25 09:35:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0002', N'4', N'58', N'2019-06-25 09:35:00.000', N'2019-06-25 10:33:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0004', N'10', N'56', N'2019-06-25 14:39:00.000', N'2019-06-25 15:35:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0014', N'12', N'50', N'2019-06-25 15:35:00.000', N'2019-06-25 16:25:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0001', N'8', N'40', N'2019-06-25 13:59:00.000', N'2019-06-25 14:39:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0001', N'TS0023', N'14', N'53', N'2019-06-25 16:25:00.000', N'2019-06-25 17:18:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0000', N'16', N'91', N'2019-06-25 16:30:00.000', N'2019-06-25 18:01:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS00', N'6', N'140', N'2019-06-25 11:39:00.000', N'2019-06-25 13:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0015', N'2', N'95', N'2019-06-25 08:30:00.000', N'2019-06-25 10:05:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0025', N'14', N'31', N'2019-06-25 15:59:00.000', N'2019-06-25 16:30:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0030', N'12', N'39', N'2019-06-25 15:20:00.000', N'2019-06-25 15:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0011', N'8', N'50', N'2019-06-25 13:59:00.000', N'2019-06-25 14:49:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0019', N'10', N'31', N'2019-06-25 14:49:00.000', N'2019-06-25 15:20:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0002', N'TS0020', N'4', N'80', N'2019-06-25 10:05:00.000', N'2019-06-25 11:25:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS0000', N'16', N'1', N'2019-06-25 16:09:00.000', N'2019-06-25 16:10:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS00', N'8', N'180', N'2019-06-25 10:59:00.000', N'2019-06-25 13:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS0005', N'4', N'45', N'2019-06-25 09:10:00.000', N'2019-06-25 09:55:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS0006', N'6', N'47', N'2019-06-25 09:55:00.000', N'2019-06-25 10:42:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS0017', N'10', N'90', N'2019-06-25 13:59:00.000', N'2019-06-25 15:29:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0003', N'TS0022', N'2', N'40', N'2019-06-25 08:30:00.000', N'2019-06-25 09:10:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0000', N'16', N'81', N'2019-06-25 17:05:00.000', N'2019-06-25 18:26:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS00', N'10', N'140', N'2019-06-25 11:39:00.000', N'2019-06-25 13:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0024', N'14', N'96', N'2019-06-25 15:29:00.000', N'2019-06-25 17:05:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0028', N'2', N'45', N'2019-06-25 08:30:00.000', N'2019-06-25 09:15:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0013', N'8', N'33', N'2019-06-25 10:13:00.000', N'2019-06-25 10:46:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0007', N'4', N'28', N'2019-06-25 09:15:00.000', N'2019-06-25 09:43:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0003', N'6', N'30', N'2019-06-25 09:43:00.000', N'2019-06-25 10:13:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0004', N'TS0016', N'12', N'90', N'2019-06-25 13:59:00.000', N'2019-06-25 15:29:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0000', N'16', N'51', N'2019-06-25 17:33:00.000', N'2019-06-25 18:24:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS00', N'8', N'170', N'2019-06-25 11:09:00.000', N'2019-06-25 13:59:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0026', N'10', N'100', N'2019-06-25 13:59:00.000', N'2019-06-25 15:39:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0027', N'2', N'70', N'2019-06-25 08:30:00.000', N'2019-06-25 09:40:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0029', N'12', N'62', N'2019-06-25 15:39:00.000', N'2019-06-25 16:41:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0012', N'6', N'40', N'2019-06-25 10:21:00.000', N'2019-06-25 11:01:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0018', N'14', N'52', N'2019-06-25 16:41:00.000', N'2019-06-25 17:33:00.000');
GO
INSERT INTO [dbo].[IMS_PATROL_TASK_TIME] ([ID], [PERSON_ID], [TASK_ID], [ORDER_NO], [SPEND_TIME], [START_TIME], [END_TIME]) VALUES (null, N'XJ0005', N'TS0021', N'4', N'41', N'2019-06-25 09:40:00.000', N'2019-06-25 10:21:00.000');
GO
